# Use of /** so that the configurations hold for controller
# managers regardless of their namespace. Usefull in multi-robot setups.
/**/controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


# ROS2 effort control example controller
/**/effort_example_controller:
  ros__parameters:
    type: EffortExampleController

    dq_filt_alpha: 0.8
    report_period: 0.0
    init_pos: [0.0, 0.4, 0.0, -0.4, 0.0, 1.2, 0.0]
    init_time: 8.0
    p_gains: [150.0, 240.0, 150.0, 240.0, 50.0, 50.0, 0.0]
    d_gains: [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]

    amplitudes: [0.0, 0.1, 0.0, -0.1, 0.0, 0.0, 0.0]
    periods: [8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]
    effort_max: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]

# Different values for the controller
/**/effort_example_controller_home0:
  ros__parameters:
    type: EffortExampleController

    dq_filt_alpha: 0.8
    report_period: 0.1
    init_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    init_time: 5.0
    p_gains: [150.0, 240.0, 150.0, 240.0, 50.0, 50.0, 0.0]
    d_gains: [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]

    amplitudes: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    periods: [8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]
    effort_max: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]

/**/effort_example_controller_home1:
  ros__parameters:
    type: EffortExampleController

    dq_filt_alpha: 0.8
    report_period: 0.1
    init_pos: [0.0, 0.6, 0.0, -1.05, 0.0, 1.45, 0.0]
    init_time: 5.0
    p_gains: [150.0, 240.0, 150.0, 240.0, 50.0, 50.0, 0.0]
    d_gains: [ 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0 ]

    amplitudes: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    periods: [8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]
    effort_max: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]

/**/effort_example_controller_home2:
  ros__parameters:
    type: EffortExampleController

    dq_filt_alpha: 0.8
    report_period: 0.1
    init_pos: [0.0, 0.7, 0.0, -1.4, 0.0, 0.95, 0.0]
    init_time: 5.0
    p_gains: [150.0, 240.0, 150.0, 240.0, 50.0, 50.0, 0.0]
    d_gains: [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]

    amplitudes: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    periods: [8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]
    effort_max: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]


/**/effort_example_controller_home3:
  ros__parameters:
    type: EffortExampleController

    dq_filt_alpha: 0.8
    report_period: 0.1
    init_pos: [0.2, 0.7, 0.0, -1.4, 0.0, 0.95, 0.0]
    init_time: 5.0
    p_gains: [150.0, 240.0, 150.0, 240.0, 50.0, 50.0, 0.0]
    d_gains: [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]

    amplitudes: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    periods: [8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]
    effort_max: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]

/**/effort_example_controller_zero:
  ros__parameters:
    type: EffortExampleController

    all_hw_interfaces: true
    dq_filt_alpha: 0.8
    report_period: 0.1
    init_pos: [-0.2, 0.9, 0.0, -1.4, 0.0, 0.95, 0.0]
    init_time: 5.0
    p_gains: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    d_gains: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    amplitudes: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    periods: [8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]
    effort_max: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]
