<?xml version="1.0"?>
<package format="3">
  <name>agimus_demo_00_kuka_controller</name>
  <version>1.0.0</version>
  <description>
    Demonstration for a simple Kuka controller using torque-only control mode.
  </description>
  <maintainer email="martin.matousek@cvut.cz">Martin Matousek</maintainer>
  <author>Martin Matousek</author>

  <license>BSD-2</license>
  <url type="website">https://www.agimus-project.eu/</url>
  <url type="repository">https://github.com/agimus-project/agimus-demos</url>
  <url type="bugtracker">https://github.com/agimus-project/agimus-demos/issues</url>
  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <exec_depend>agimus_demos_common</exec_depend>
  <exec_depend>agimus_demos_common_kuka</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>lbr_demos_cpp</exec_depend>
  <exec_depend>ros2launch</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <controller_interface plugin="${prefix}/controller_plugins.xml" />
  </export>
</package>
