---
agimus_controller_node:
  ros__parameters:
    ocp:
      dt: 0.01
      horizon_size: 10
      dt_factor_n_seq:
        n_steps: [10]
        factors: [1]
      armature: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      max_qp_iter: 200
      max_iter: 20
      activate_callback: false
      termination_tolerance: 0.001
    publish_debug_data: true
    constant_delay: false
    rate: 100.0
    free_flyer: false
    collision_as_capsule: false
    self_collision: false
    collision_pairs_names: [cp_1]
    cp_1:
      first: lbr_link_7_0
      second: obstacle1_0
    robot_attachment_frame: universe
