---
running_model:
  class: IntegratedActionModelEuler
  differential:
    class: DifferentialActionModelFreeFwdDynamics
    costs:
    - name: control_reg
      update: true
      weight: 1.0
      active: true
      cost:
        class: CostModelResidual
        activation:
          class: ActivationModelWeightedQuad
          weights: 1.0
        residual:
          class: ResidualModelControl
    - name: state_reg
      update: true
      weight: 1.0
      cost:
        class: CostModelResidual
        activation:
          class: ActivationModelWeightedQuad
          weights: 1.0
        residual:
          class: ResidualModelState
    - name: goal_tracking
      update: true
      weight: 1.0
      cost:
        class: CostModelResidual
        activation:
          class: ActivationModelWeightedQuad
          weights: 1.0
        residual:
          class: ResidualModelFramePlacement
          id: 0
    - name: distance
      update: false
      weight: 0.05
      publish_residual: true
      cost:
        class: CostModelResidual
        activation:
          class: ActivationModelQuadExp
          alpha: 1e-4   # 1cm squared
        residual:
          class: ResidualDistanceCollision
          collision_pair: [lbr_link_7_0, obstacle1_0]
    constraints:
    - name: collision
      constraint:
        class: ConstraintModelResidual
        lower: 0.01   # cm
        upper: inf
        residual:
          class: ResidualDistanceCollision
          collision_pair: [lbr_link_7_0, obstacle1_0]

terminal_model:
  class: IntegratedActionModelEuler
  differential:
    class: DifferentialActionModelFreeFwdDynamics
    costs:
    - name: state_reg
      update: true
      weight: 0.0
      cost:
        class: CostModelResidual
        activation:
          class: ActivationModelWeightedQuad
          weights: 1.0
        residual:
          class: ResidualModelState
    - name: goal_tracking
      update: true
      weight: 0.0
      active: false
      cost:
        class: CostModelResidual
        activation:
          class: ActivationModelWeightedQuad
          weights: 1.0
        residual:
          class: ResidualModelFramePlacement
          id: 0
    - name: distance
      update: false
      weight: 0.0
      cost:
        class: CostModelResidual
        activation:
          class: ActivationModelQuadExp
          alpha: 1e-4   # 1cm squared
        residual:
          class: ResidualDistanceCollision
          collision_pair: [lbr_link_7_0, obstacle1_0]
